ably/ably-ui

Gemfile.lock, cypress/integration/core/slider/behaviour.js, lib/ably_ui/version.rb, package.json, preview/Gemfile, preview/Gemfile.lock, preview/app/javascript/packs/slider.js, preview/app/views/components/slider_react.html.erb, preview/app/views/components/slider_vw.html.erb, preview/app/views/pages/index.html.erb, preview/package.json, preview/yarn.lock, src/core/Slider/component.html.erb, src/core/Slider/component.js, src/core/Slider/component.jsx, src/core/react-renderer.js, src/core/scripts.js
----
Adds a React version of a Slider component needed for Athlon work.
----
See commits.
----
Component has been added under `/components/slider`
----
----
----
=> Add React Slider

src/core/MeganavItemsSignedIn/component.html.erb, src/core/MeganavItemsSignedIn/component.jsx
----
https://ably.atlassian.net/browse/WEB-2074
----
Use preview label instad of beta
----
check user dropdown menu public website wording should be 'preview', this test requires logged in user
----
----
----
=> [WEB-2074] Use Preview instead of beta label in website meganav

Gemfile.lock, cypress/integration/core/company_autocomplete/behaviour.spec.js, lib/ably_ui/version.rb, modules-config.js, package.json, pre-release.sh, preview/Gemfile, preview/Gemfile.lock, preview/app/controllers/api/company_data_controller.rb, preview/app/javascript/styles/application.css, preview/app/views/components/company_autocomplete_vw.html.erb, preview/app/views/pages/index.html.erb, preview/config/routes.rb, preview/package.json, preview/yarn.lock, src/core/CompanyAutocomplete/component.css, src/core/CompanyAutocomplete/component.js
----
https://ably.atlassian.net/browse/DEX-55
----
Adds a component to autocomplete company names.
----
The widget always returns max 5 results. You can choose by clicking on the result or by pressing Enter or Space on it. You can navigate the results with the Up/Down arrows and Tab. Escape closes the dropdown as well as clicking outside the dropdown.
Note the version in the example page uses a fake API.
----
----
----
=> [DEX-55] Company autocomplete

Gemfile.lock, lib/ably_ui/version.rb, package.json, preview/Gemfile, preview/Gemfile.lock, preview/package.json, preview/yarn.lock, src/core/MeganavContentDevelopers/component.html.erb, src/core/MeganavContentDevelopers/component.jsx
----
https://ably.atlassian.net/browse/WEB-2147
----
Added periodic table link to the Developers > Explore menu in the meganav component 
----
----
----
----
=> [WEB-2147] Add periodic table link to meganav menu

preview/app/views/components/company_autocomplete_vw.html.erb, src/core/CompanyAutocomplete/component.js
----
On some fields, browsers will show an autocomplete for the company when our autocomplete is enabled. We disable this (but not autofill—this is just when people focus into the field, not when they have saved fields).
----
----
----
----
----
=> Set autocomplete to off when component enabled

tailwind.config.js
----
Adds spacing values into `max-width` as we use them in a couple of places now.
----
----
----
----
----
=> Add spacing values to max-w- definition in tailwind

Gemfile.lock, cypress/integration/core/footer/__snapshots__/snapshots.js.snap, lib/ably_ui/version.rb, package.json, preview/Gemfile, preview/Gemfile.lock, preview/package.json, preview/yarn.lock, src/core/Footer/component.html.erb, src/core/Footer/component.jsx, src/core/MeganavContentUseCases/component.html.erb, src/core/MeganavContentUseCases/component.jsx
----
https://ably.atlassian.net/browse/WEB-2179
----
added links described in the ticket
----
in the preview app, naviage to:
https://ably-ui-add-links-kafka-kp3rmz.herokuapp.com/components/meganav
and 
https://ably-ui-add-links-kafka-kp3rmz.herokuapp.com/components/footer
----
Cypress is not generating all snapshot required to specs pass, there are other failing specs not related to this change
----
----
=> [WEB-2179] Add links to Kafka page on nav and footer

Gemfile.lock, cypress/integration/core/footer/__snapshots__/snapshots.js.snap, lib/ably_ui/version.rb, package.json, preview/Gemfile, preview/Gemfile.lock, preview/package.json, preview/yarn.lock, src/core/Footer/component.html.erb, src/core/Footer/component.jsx
----
https://ably.atlassian.net/browse/WEB-2213
----
just updated the invite url (check ticket related comments) and fixed some cypress snapshots tests
----
Naviagate to `/components/footer`
----
----
----
=> [WEB-2213] update discord invite url

preview/app/views/pages/index.html.erb, src/core/styles/text.css
----
List styles bugs found during topic page work.
----
----
----
----
----
=> Correct List styles

preview/app/views/pages/index.html.erb, src/core/Code/component.css, src/core/styles/properties.css, src/core/styles/text.css, tailwind.config.js
----
Updates to latest 
----
----
----
----
----
=> Update to latest code font styling

Gemfile.lock, cypress/integration/core/code/__snapshots__/snapshots.js.snap, lib/ably_ui/version.rb, package.json, preview/Gemfile, preview/Gemfile.lock, preview/package.json, preview/yarn.lock, src/core/Code/component.jsx, src/core/Code/component.rb
----
Use new code styling on code component
----
----
----
----
----
=> Use new code styling on code component

preview/app/components/colours_list_component.rb, src/core/styles/properties.css, tailwind.config.js
----
[MAW-9](https://ably.atlassian.net/jira/software/projects/MAW/boards/128?selectedIssue=MAW-9) Add 'Extra Light Grey' colour to Ably UI
Asana - https://app.asana.com/0/1202054865216493/1202166451287285/f
----
This is requested by Design Team - Additional colour ref was added to DS but not requested as update for Ably UI.
----
Check Ably-UI page if the correct colour reflects
----
----
----
=> Add 'Extra Light Grey' colour to Ably UI

src/core/MeganavContentUseCases/component.html.erb, src/core/MeganavContentUseCases/component.jsx
----
We need to update the Meganav to link to the Fintech page.
See https://ably-real-time.slack.com/archives/C02T5DSQHEG/p1651231511609619 for details.
----
----
Checkout repo and inspect the components, order should be:
Left column:
1. EdTech
2. Virtual Events
3. Sports & Media
4. Fintech
5. Gaming
6. Automotive, Logistics & Mobility
Right column:
1. B2B Platforms
2. Healthcare
3. eCommerce & Retail
4. IOT & Connected Devices
5. Asset Tracking
6. Extend Kafka to the edge
----
----
----
=> Add Fintech to Use Cases panel and reorder items

.github/workflows/release-tag.yml
=> add PR write permission

preview/app/javascript/styles/application.css, preview/app/views/components/icon/_arguments.html.erb, preview/app/views/pages/index.html.erb, src/core/styles/forms.css
----
Migrate textarea styles from website.
----
----
As review apps are not currently working for AblyUI, please checkout locally. Textarea has been added in the "Forms section" on the index.
----
----
----
=> Add textarea styles

Gemfile.lock, lib/ably_ui/version.rb, package.json, preview/Gemfile, preview/Gemfile.lock, preview/package.json, preview/yarn.lock, src/core/styles/text.css
----
Ticket [MAW-26](https://ably.atlassian.net/jira/software/projects/MAW/boards/128?assignee=621c83a5302c6b006af0afeb&selectedIssue=MAW-26)
----
Update H4 property to be uppercase as per the Linear Design
----
----
----
----
=> Ably UI: H4 text need to be uppercase

.github/workflows/release.yml, .github/workflows/update-dependents.yml, .github/workflows/update-preview.yml, scripts/release.sh, scripts/update-preview.sh
----
This addresses issues with running current actions.
----
----
We need to merge + trigger a release to test e2e.
----
----
----
=> Actions fixes

Gemfile.lock, lib/ably_ui/version.rb, package.json, preview/Gemfile, preview/Gemfile.lock, preview/package.json, preview/yarn.lock, src/core/Logo/component.jsx
----
Standard nanoid depends on browser crypto API.
We don't need the security for use case and using it breaks Gatsby SSR with not up-to-date jsdoms.
----
----
----
----
----
=> Use nanoid non-secure

preview/app/components/colours_list_component.rb, preview/app/views/pages/index.html.erb, src/core/Code/component.css, src/core/fonts/source-code-pro.css, src/core/styles/properties.css, src/core/styles/text.css, tailwind.config.js
----
Implement:
https://app.asana.com/0/1202054865216493/1202146409149931/f
https://app.asana.com/0/1202054865216493/1202146409149933/f
Additionally:
- update paragraph text styles to correct color
- move Source Code Pro import to a separate file
----
----
All changes can be review in the preview app (remotely or locally)
----
----
----
=> Linear design system updates

Gemfile.lock, lib/ably_ui/version.rb, package.json, preview/Gemfile, preview/Gemfile.lock, preview/app/controllers/components_controller.rb, preview/app/views/components/meganav_vw.html.erb, preview/app/views/layouts/application.html.erb, preview/package.json, preview/yarn.lock, src/core/Meganav/component.js, src/core/Meganav/component.jsx, src/core/MeganavItemsSignedIn/component.html.erb, src/core/MeganavSearchAutocomplete/component.js
----
This improves the way we pass the AddSearch api key so it's more inline what we can do in Voltaire and website.
----
----
----
----
----
=> Pass api key to meganav directly

Gemfile.lock, cypress/integration/core/meganav/behaviour.spec.js, lib/ably_ui/version.rb, package.json, preview/Gemfile, preview/Gemfile.lock, preview/package.json, preview/yarn.lock, src/core/MeganavSearchPanel/component.html.erb, yarn.lock
----
- fix ruby search panel not having the correct URL
- update addsearch to make it compatible with SSR in Voltaire
----
----
- on the ruby search, entering a query and pressing enter now takes you to the correct url (`/search?q=query`)
- update does not break SSR in Voltaire
----
----
----
=> Search panel fixes

src/core/MeganavContentPlatform/component.html.erb, src/core/MeganavContentPlatform/component.jsx
----
ERK-218
----
Updates Meganav to show Atomic Examples links under the Platform section. It replaces the existing "Our Features" section with "Examples"
----
Run locally & in theory you should see the updated links.
----
----
----
=> feat: Update Meganav to show atomic examples

Gemfile.lock, lib/ably_ui/version.rb, package.json, preview/Gemfile, preview/Gemfile.lock, preview/package.json, preview/yarn.lock, src/core/MeganavSearchSuggestions/component.js
----
This fixes two issues with the below bar:
First, it adds support for mousewheel scroll (mostly for testing), second, it fixes the bar scrolling way to far when the screen was resized (I've moved a calculation from init to on action).
----
----
- mouse wheel now allows you to scroll through suggestions
- when you open the tab, then open the browser inspector and the mobile inspector, the suggestions don't go immedietely off screen on drag
----
----
----
=> Support mousewheel on search suggestions

src/core/Flash/component.jsx
----
This so we can use it without BackendFlashes, which are specific to rendering from our ViewComponents.
----
----
----
----
----
=> Expose Flashes as component

preview/app/controllers/components_controller.rb, src/core/MeganavContentUseCases/component.html.erb, src/core/MeganavContentUseCases/component.jsx, src/core/icons/icon-multi-user-spaces-col.svg
----
https://ably.atlassian.net/browse/WEB-2569
----
added item to user cases menu
----
check the menu in the preview app and verify that element is presented in that app
----
----
----
=> [WEB-2569] Add multi user spaces  link to meganav

src/core/MeganavContentDevelopers/component.html.erb, src/core/MeganavContentDevelopers/component.jsx
----
https://ably.atlassian.net/browse/WEB-2566
----
just a quick typo fix
----
Check developer tab in meganav menu, it should display `GitHub`
----
----
----
=> [WEB-2566] Capitalize H for GitHub nav in developers meganav section

src/core/FeatureFooter/component.html.erb
----
https://ably.atlassian.net/browse/WEB-2592
----
just an update to the pricing features for free plans
----
check the FeatureFooter component  in the preview app
----
----
----
=> [WEB-2592] change pricing feature for ably api free plan

Gemfile.lock, cypress/integration/core/flash/__snapshots__/snapshot.js.snap, lib/ably_ui/version.rb, package.json, preview/Gemfile, preview/Gemfile.lock, preview/package.json, preview/yarn.lock, src/core/styles/text.css
----
[MAW-341](https://ably.atlassian.net/browse/MAW-341?atlOrigin=eyJpIjoiYjRhZjUwYmMxZThhNGVlMmFiOTU3NTYzZThkOGE4NzciLCJwIjoiaiJ9)
----
update the ui-link to be same as the design
----
Open ably-ui site and check the links part of the the sample links are updated
----
----
----
=> Activate new link design

Gemfile.lock, lib/ably_ui/version.rb, package.json, preview/Gemfile, preview/Gemfile.lock, preview/package.json, preview/yarn.lock, src/core/CustomerLogos/component.html.erb, src/core/CustomerLogos/component.jsx, src/core/CustomerLogos/component.rb
----
This PR extends the company logos component, so that we can add additional css for custom style purposes.
It also addresses an issue with local development, where foreman was never explicitly listed as a dependency.
----
----
----
----
----
=> Extend Company Logos Component

preview/app/controllers/components_controller.rb, src/core/MeganavContentDevelopers/component.html.erb, src/core/MeganavContentDevelopers/component.jsx, src/core/icons/icon-display-integrations-col.svg
----
https://ably.atlassian.net/browse/WEB-2622
----
added integration link to the meganav menu
----
in the preview app, check proper section /components/meganav
----
----
----
=> [WEB-2622] Add integrations link to developers section of the meganav menu

src/core/MeganavSearchSuggestions/component.html.erb
----
https://ably.atlassian.net/browse/WEB-2623
----
just a update of the platform link of the meganav search section
----
----
----
----
=> [WEB-2623] Fix platform link of the meganav search results section

src/core/MeganavContentUseCases/component.html.erb, src/core/MeganavContentUseCases/component.jsx
----
https://ably.atlassian.net/browse/WEB-2621
----
just capitalize FinTech un the meganav menu
----
----
----
----
=> [WEB-2621] Capitalize FinTech

Gemfile.lock, README.md, cypress/integration/core/dropdown_menu/__snapshots__/snapshot.js.snap, cypress/integration/core/dropdown_menu/behaviour.js, cypress/integration/core/dropdown_menu/snapshot.js, lib/ably_ui/version.rb, modules-config.js, package.json, preview/Gemfile, preview/Gemfile.lock, preview/app/controllers/components_controller.rb, preview/app/javascript/packs/application.js, preview/app/javascript/packs/dropdown-menu-react.js, preview/app/views/components/dropdown_menu_react.html.erb, preview/app/views/pages/index.html.erb, preview/package.json, preview/yarn.lock, src/core/DropdownMenu/component.jsx
----
EDX-371
----
This PR brings over the Dropdown Menu created by @Glazy in the Website repo to Ably UI for reuse.
I have made a few changes as follows:
* Created a Menu Link component
* Added optional props to style the Trigger
* Added optional props to style the Content
----
----
----
----
=> [EDX-371] Dropdown menu component

src/core/FeatureFooter/component.html.erb
----
https://ably.atlassian.net/browse/WEB-2614
----
just a couple updates of the copies in website
----
Navigate to website homepage and verify copies were updated (see jira ticket)
----
----
----
=> [WEB-2614] Homepage copy updates

tailwind.config.js
----
Add missing spacing value to tailwind config.
----
----
----
----
----
=> Add missing spacing value to tailwind config

.npmrc, Gemfile.lock, lib/ably_ui/version.rb, package.json, preview/Gemfile, preview/Gemfile.lock, preview/app/controllers/components_controller.rb, preview/package.json, preview/yarn.lock, src/core/icons/icon-gui-check-circled-fill-black.svg
----
No single ticket but its related to this [ERK-297](https://ably.atlassian.net/browse/ERK-297?atlOrigin=eyJpIjoiN2FhYThkMGY2ZDE2NDVmNzlmZWFkMzQyMmY2ZWM5NzkiLCJwIjoiaiJ9)
----
Add new icon
----
New Icon shoild be visible here - https://ably-ui-erk-297-elram3xiis4alm.herokuapp.com/components/icon
----
----
----
=> Add another check icon for black check

Gemfile.lock, README.md, cypress/integration/core/meganav/parity.spec.js, lib/ably_ui/version.rb, package.json, preview/Gemfile, preview/Gemfile.lock, preview/package.json, preview/yarn.lock, src/core/MeganavContentDevelopers/component.html.erb
----
This PR makes the following changes:
* Updates the Meganav dropdown for the ViewComponent Developers panel to match the React one
* Changes the way the cypress test finds the mobile panel (so that the name of the panel can be changed without having to change the id or any other info.)
* Updates the README to show the current way of using the local gem file.
----
----
----
----
----
=> Cypress test fixes

Gemfile.lock, cypress/integration/core/meganav/parity.spec.js, lib/ably_ui/version.rb, package.json, preview/Gemfile, preview/Gemfile.lock, preview/package.json, preview/yarn.lock, src/core/Meganav/component.json, src/core/Meganav/component.rb
----
MAW-397
This PR updates the text on the Meganav panel from "Usecases & Solutions" to "Solutions"
----
----
----
----
----
=> feat: Renames Meganav section to Solutions

preview/Gemfile.lock
=> fix: Fixes the issue with release

src/core/MeganavContentUseCases/component.html.erb, src/core/MeganavContentUseCases/component.jsx
----
https://ably.atlassian.net/browse/WEB-2785
----
Added new solutions to the meganav
----
----
----
----
=> [WEB-2785] Add new solutions to meganav

Gemfile.lock, lib/ably_ui/version.rb, package.json, preview/Gemfile, preview/Gemfile.lock, preview/package.json, preview/yarn.lock, src/core/MeganavContentUseCases/component.html.erb, src/core/MeganavContentUseCases/component.jsx
----
WEB-2871
----
Rename to Live Chat
----
----
----
----
=> Rename to Live Chat

Gemfile.lock, lib/ably_ui/version.rb, package.json, preview/Gemfile, preview/Gemfile.lock, preview/package.json, preview/yarn.lock, src/core/Meganav/component.css
----
[MAW-422](https://ably.atlassian.net/browse/MAW-422)
----
Update column gap from 8px to 16px
----
https://ably-ui-maw-422-eiwjw96voqcip1.herokuapp.com/components/meganav
----
----
----
[MAW-422]: https://ably.atlassian.net/browse/MAW-422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MAW-422] - Adjust space between icons and texts on meganav

.tool-versions, Gemfile.lock, lib/ably_ui/version.rb, package.json, preview/Gemfile, preview/Gemfile.lock, preview/package.json, preview/yarn.lock
----
After merging some critical updates to [nokogiri](https://github.com/ably/ably-ui/pull/267), [rack](https://github.com/ably/ably-ui/pull/266), [activesupport](https://github.com/ably/ably-ui/pull/265) and [webpack](https://github.com/ably/ably-ui/pull/264), I wasn't able to run ably ui with the existing NodeJS version - `14.15.4`. Also this version is no longer supported. 
So I have updated the nodejs version to 16.17.0.
I am able to run ably-ui locally with no issues. And it is also running fine on the deployment [here](https://ably-ui-update-node-ver-tb1mcq.herokuapp.com/).
----
----
----
----
----
=> Update node version to 16.17.0

.github/workflows/release.yml, .github/workflows/update-versions.yml
----
The github actions on this repo have been failing for a few months due to out of date node versions being used. This PR updates the node version to `16.17.0`.
----
----
----
----
----
=> Update node version on github actions

Gemfile.lock, lib/ably_ui/version.rb, package.json, preview/Gemfile, preview/Gemfile.lock, preview/app/views/pages/index.html.erb, preview/package.json, preview/yarn.lock, src/core/styles/text.css
----
MAW-476
----
This change updates the `h4` style to not transform to uppercase automatically.
----
----
----
----
=> feat: Updates h4 to be non capitalised

Gemfile.lock, lib/ably_ui/version.rb, package.json, preview/Gemfile, preview/Gemfile.lock, preview/package.json, preview/yarn.lock, src/core/MeganavContentDevelopers/component.html.erb, src/core/MeganavContentDevelopers/component.jsx
----
This PR adds a link in the meganav for the multiplayer guide.
----
----
----
----
----
=> feat: Add link in meganav for ref guide multiplayer

Gemfile.lock, cypress/integration/core/footer/__snapshots__/snapshots.js.snap, cypress/integration/core/meganav/parity.spec.js, lib/ably_ui/version.rb, package.json, preview/Gemfile, preview/Gemfile.lock, preview/package.json, preview/yarn.lock, src/core/Footer/component.html.erb, src/core/Footer/component.jsx, src/core/MeganavContentProducts/component.jsx
----
[WEB-3241](https://ably.atlassian.net/browse/WEB-3241)
----
----
----
----
----
[WEB-3241]: https://ably.atlassian.net/browse/WEB-3241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WEB-3241: Remove link to the hub page in footer

Gemfile.lock, lib/ably_ui/version.rb, package.json, preview/Gemfile, preview/Gemfile.lock, preview/package.json, preview/yarn.lock, yarn.lock
----
Upgrade to react 18.
----
----
----
----
----
=> Upgrade to react 18

Gemfile.lock, cypress/e2e/core/footer/__snapshots__/snapshots.cy.js.snap, lib/ably_ui/version.rb, package.json, preview/.tool-versions, preview/Gemfile, preview/Gemfile.lock, preview/package.json, preview/yarn.lock, src/core/Footer/component.html.erb, src/core/Footer/component.jsx, src/core/MeganavContentDevelopers/component.html.erb, src/core/MeganavContentDevelopers/component.jsx
----
[ACT-86](https://ably.atlassian.net/browse/ACT-86)
----
Update the links in the header and footer to the new sdks docs page
[ACT-86]: https://ably.atlassian.net/browse/ACT-86?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ACT-86] Meganav and footer has new sdk page link

.gitignore, Gemfile.lock, README.md, lib/ably_ui/version.rb, package.json, preview/Gemfile, preview/Gemfile.lock, preview/babel.config.js, preview/config/webpack/development.js, preview/config/webpack/environment.js, preview/package.json, preview/tailwind.config.js, preview/yarn.lock, src/core/Showcase/component.html.erb, src/core/Showcase/component.js, src/core/Uptime/component.css, src/core/styles/text.css, tailwind.config.js, tailwind.extend.js, yarn.lock
----
https://ably.atlassian.net/browse/ACT-119
----
----
----
----
----
=> [ACT-119] Tailwind 3 upgrade

src/core/MeganavContentProducts/component.html.erb, src/core/MeganavContentProducts/component.jsx
=> COL-628:  "Early access" instead of "Pre release" on meganav  for LiveSync

Gemfile.lock, lib/ably_ui/version.rb, package.json, preview/Gemfile, preview/Gemfile.lock, preview/package.json, preview/yarn.lock, src/core/FeaturedLink/component.jsx
Motivation
----
Required in the website to be able to pass an `onClick` handler to `<FeaturedLink>` components.
----
See commits for details
----
The new getting started PR on the website uses the pre-release from this PR.
----
----
=> Add support for onClick to FeaturedLink

src/core/Accordion/Accordion.stories.tsx, src/core/Accordion/component.tsx
----
Accordion is being used on multiple places in a few of Ably's projects, so it should be implemented in AblyUI as a generic component, in order not to recreate it every time.
----
Added Accordion component to AblyUI Core folder.
----
In preview app find Accordion link under Components, click on it and try out the component for yourself.
----
----
=> [FEAT]: add accordion to core folder

src/core/Table/Table.tsx, src/core/Table/TableCell.tsx, src/core/Table/TableRow.tsx, src/core/Table/index.ts, src/core/Table/stories/Table.stories.tsx, src/core/Table/stories/data.tsx, src/core/Tooltip/Tooltip.stories.tsx, src/core/Tooltip/component.tsx
https://ably.atlassian.net/jira/software/projects/WEB/boards/172?selectedIssue=WEB-3581
This PR introduces the `Table` and `Tooltip` components into `ably-ui`, migrated from the [pricing page](https://ably.com/pricing) on Ably.com. Comparing to their original forms, the following changes have been made:
**Table**
- a restructuring from a single component that takes data props to an open set of stylised components for each of the constituent parts of a table (row, cell etc). This takes inspiration from [Radix's approach](https://www.radix-ui.com/themes/docs/components/table), Radix being a candidate for further adoption later on. Look at `PricingPageTable` in `src/core/Table/stories` for example of how these components are used.
- a switch from a `display: grid` structure to a semantic …
=> [WEB-3581] Table migration

src/core/Slider.tsx, src/core/Slider/Slider.stories.tsx, src/core/Slider/component.css
We find ourselves in need of a generic slider component, which will accept slides as children, and can be used on multiple places in Ably projects.
[WEB-3583](https://ably.atlassian.net/browse/WEB-3583)
Added React and Tailwind Slider component.
Check it out in Storybook
[WEB-3583]: https://ably.atlassian.net/browse/WEB-3583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3583] Slider

.github/dependabot.yml
Motivation
Keeping this one fresh and as up-to-date as possible so our downstream projects aren't held back by an outdated supply chain
See commit for details.
Past experience says this needs to be merged to `main` first
=> Add dependabot.yml to help keep packages fresh

.github/workflows/push.yml, .github/workflows/release.yml, .github/workflows/update-versions.yml, .storybook/main.ts, .storybook/preview.tsx, .tool-versions, package.json, public/mockServiceWorker.js, src/core/Meganav/Meganav.stories.tsx, yarn.lock
Jira N/A. The motivation is to unblock us on a lot of upgrade paths, since we were getting a number of Dependabot PRs that we've had to close, mostly because of Node 16 holding us back.
With this we gain a lot of possibilities for things like visual testing built in which we can explore later, but this is mainly a deps branch.
Upgraded Node to latest LTS, ran the Storybook 8 migration process, upgraded MSW and Vite to match.
Run `yarn storybook` and it's snazzier
=> chore: upgrade Storybook to 8, MSW to 2, Vite to 5, Node to 20

package.json, src/core/styles.components.css
Very small change. Just tinkers with the `ui-*-spacing` CSS classes to reflect [this](https://www.figma.com/design/knbmbXitJtMlp4dBvs79AT/04---Layout?node-id=602-48&t=93KVSTO3bw6hC09D-1) Figma spec better.
=> chore: update ui-*-spacing classes to reflect design system

package.json, src/core/MeganavContentProducts.tsx
Chat SDK (Beta) is launching 🎉. See WEB-3881
Review in Storybook
=> [WEB-3881] Add "Chat (Beta)" to the meganav products menu

package.json, src/core/Footer.tsx, src/core/Footer/__snapshots__/Footer.stories.tsx.snap, src/core/Meganav/__snapshots__/Meganav.stories.tsx.snap, src/core/MeganavContentProducts.tsx, src/core/MeganavContentUseCases.tsx
WEB-3968
Since the changes of the URLs, the navigation will be updated for https://ably.com/chat and https://ably.com/pubsub
- Open storybook
- Check Meganav Navigation for Live Chat and Pubsub the URL should be updated
- Check footer navigation for pubsub the URL should be updated
=> Update navigation to change  /chat & /pubsub URLs

.gitignore, global.d.ts, package.json, src/core/Accordion.tsx, src/core/ConnectStateWrapper.tsx, src/core/ContactFooter.tsx, src/core/CookieMessage.tsx, src/core/DropdownMenu.tsx, src/core/FeaturedLink.tsx, src/core/Flash.tsx, src/core/Footer.tsx, src/core/Meganav.tsx, src/core/Meganav/component.js, src/core/MeganavContentCompany.tsx, src/core/MeganavContentProducts.tsx, src/core/MeganavItemsDesktop.tsx, src/core/MeganavItemsMobile.tsx, src/core/SignOutLink.tsx, src/core/Slider.tsx, src/core/Status.tsx, src/core/Table/data.tsx, src/core/hubspot-chat-toggle.js, tsc.js, tsconfig.json, yarn.lock
N/A
We have type declaration files on `voltaire` and `docs` which we currently have to manually maintain (not `website` yet as there's no TS there). This means that if a component in `ably-ui` is added or changed, we have to remember to replicate those changes downstream, which is a) tedious and b) potentially misleading if declarations are out of date.
This PR automates this process by generating TS declarations at build time, concatenating them, and then inserting them [into the package](https://www.npmjs.com/package/@ably/ui/v/14.4.0-dev.1b6b1db?activeTab=code). Some light modifications are carried out on these declarations to hammer them into this package's slightly unusual module structuring.
To allow `tsc` to generate the declarations without erroring, a bunch of TS errors have also …
=> [WEB-3951] Bundle TS declarations in with package

package.json, src/core/Accordion.tsx, src/core/Accordion/Accordion.stories.tsx, src/core/Accordion/__snapshots__/Accordion.stories.tsx.snap, src/core/Accordion/types.ts, src/core/styles/colors/Colors.stories.tsx, src/core/styles/colors/__snapshots__/Colors.stories.tsx.snap, src/core/styles/colors/types.ts, src/core/styles/properties.css
https://ably.atlassian.net/browse/WEB-3841
Enhances the existing `Accordion` component with additional styling and functionality. The [affiliated Storybook page](https://ably.github.io/ably-ui/?path=/docs/js-components-accordion--docs) does a good job of explaining the new functionality.
This is big enough to warrant a minor version bump, there will be breaking changes downstream in `voltaire`, but few of them. Also, this is one of two PRs for Pricing - the next will involve dropdowns and input fields. 14.6.0 won't release until that and any subsequent fixes.
Take a look at the Storybook link.
=> [WEB-3841] Revamped Accordion to include theming, dynamic sizing, icons

package.json, src/core/styles/buttons.css
There's an ongoing issue with Tailwind involving using `dark:` class prefixes with the `apply` directive ([relevant conversation](https://github.com/tailwindlabs/tailwindcss/discussions/2917)), which I discovered upon including version `15.0.0` in `voltaire`. Since there seems to be no official resolution to this - this PR steps around that.
In `buttons.css`, instead of using `dark:` prefixes for classes, break classes up so that we have a separate set nested under `.ui-theme-dark` (which is the top level theme class) containing the dark classes without prefixes. Tbh, this isn't entirely unwelcome as the classes in question were quite long and unwieldy in the editor - the main issue though is that this obviously differs from Tailwind's documented approach.
Hard to say at the moment as the …
=> [WEB-4122] 15.0.1 - Button CSS dark apply fix
