- Gemfile.lock
- cypress/integration/core/footer/__snapshots__/snapshots.js.snap
- cypress/integration/core/showcase/__snapshots__/screenshots.js.snap
- cypress/integration/core/showcase/__snapshots__/snapshots.js.snap
- cypress/integration/core/uptime/__snapshots__/snapshots.js.snap
- lib/ably_ui/version.rb
- package.json
- preview/Gemfile
- preview/Gemfile.lock
- preview/package.json
- preview/yarn.lock
- src/core/Footer/component.html.erb
- src/core/Footer/component.jsx
- src/core/MeganavContentDevelopers/component.html.erb
- src/core/MeganavContentDevelopers/component.jsx
----
Documentation now lives `/docs`, and no longer under `/documentation`. See WEB-2175 for more information.
----
Updated all documentation likes to be `/docs`.
----
Confirm the documentation links go to `/docs` directly.
----
----
> [WEB-2175] Documentation now lives under /docs

- src/core/MeganavContentDevelopers/component.html.erb
- src/core/MeganavContentDevelopers/component.jsx
Motivation
----
All our own properties are served over HTTPS so we should link to them like this and save the clients a needless redirect.
----
Updated two references from `http://status.ably.com` to `https://status.ably.com`. See commit for details.
----
The status links in the meganav should be https.
----
----
> [FIX] Links to status.ably.com should be using https

- .npmrc
- Gemfile.lock
- lib/ably_ui/version.rb
- package.json
- preview/Gemfile
- preview/Gemfile.lock
- preview/package.json
- preview/yarn.lock
- src/core/MeganavContentPlatform/component.html.erb
- src/core/MeganavContentPlatform/component.jsx
----
WEB-2689
----
Remove Live Charts and Add Chat Admin Privileges for Mega Nav for both JS and erb
Screenshot
----
- Check here
JS: https://ably-ui-web-2689-tcp1hyds64yiu.herokuapp.com/components/meganav
Rails:  https://ably-ui-web-2689-tcp1hyds64yiu.herokuapp.com/components/meganav?framework=vw
----
----
----
> WEB-2689 - Update meganav for atomic examples to include Chat Admin Privileges

- Gemfile.lock
- lib/ably_ui/version.rb
- package.json
- preview/Gemfile
- preview/Gemfile.lock
- preview/app/views/components/code_react.html.erb
- preview/app/views/components/code_vw.html.erb
- preview/package.json
- preview/yarn.lock
- src/core/utils/syntax-highlighter-registry.js
- src/core/utils/syntax-highlighter.js
----
Kotlin is not added yet in ably-ui and is being used in docs
Issue reported [here](https://ably-real-time.slack.com/archives/C01LR5XFHFX/p1681672091395959)
----
Add Kotlin in the syntax highlighter and add examples so users can test
the user can use `kotlin` or `kt` as keyword for this language
----
Kotlin added here - https://ably-ui-add-kotlin-lang-t7xpqz.herokuapp.com/components/code
Rails - https://ably-ui-add-kotlin-lang-t7xpqz.herokuapp.com/components/code?framework=vw
----
----
----
> Add Kotlin in the Syntax Highlighter

- Gemfile.lock
- lib/ably_ui/version.rb
- package.json
- preview/Gemfile
- preview/Gemfile.lock
- preview/package.json
- preview/yarn.lock
The released version is always based on the GitHub tag, but to avoid confusion it's good to update it in the repo as well.
> Use latest version of ably ui in repo

- .github/workflows/update-versions.yml
- scripts/update-dependents.sh
Fix update versions action which on `release` and updates the values of versions for the preview up and library https://github.com/ably/ably-ui/actions/runs/7061490420. This is separate to the releasing because it sometimes takes a while for ruby gems to update the package availability - so we do it as a separate step.
I've also updated update-dependents to properly fail if the curl fails. This doesn't work however, as we need to obtain a valid REGISTRY_TOKEN.
> Fix update versions action

- Gemfile.lock
- ably-ui.gemspec
Motivation
----
#310 failed to release because the `Gemfile.lock` wasn't correct and so the release action just failed. This PR ultimately just updates the `Gemfile.lock` so we can get a new version published (13.2.1)
> [FIX] Bundler & Gemfile issues preventing release

- .github/workflows/release.yml
Motivation
----
After locking down the `required_ruby_version` in #312 the `release` action fails as it was pinned at Ruby 3.0
----
See commit for details
> [FIX] Bump Ruby version used in release action

- package.json
- src/core/Accordion.tsx
- src/core/Expander.tsx
- src/core/Expander/Expander.stories.tsx
- src/core/Slider.tsx
- src/core/Slider/Slider.stories.tsx
https://ably.atlassian.net/browse/WEB-3571
A bunch of small changes to support QA changes for Compare Pages in `voltaire`, the commits are quite granular but to summarise:
- added an `Expander` component, which allows a height limit to be set on a bit of content. If larger, then the content can be expanded. If not, then it displays as is.
- various TS typing and DOM hierarchy fixes
Example of `Expander`:
> [WEB-3571] Miscellaneous compare page iterations I

- package.json
- src/core/Accordion.tsx
- src/core/Expander.tsx
- src/core/Slider.tsx
- src/core/Table.tsx
- src/core/Table/Table.tsx
- src/core/Table/TableCell.tsx
- src/core/Table/data.tsx
https://ably.atlassian.net/browse/WEB-3571
This PR contains a set of relatively miscellaneous changes to `ably-ui` to support the latest (and hopefully for now, last) round of compare page QA iterations on `voltaire`.
The commit messages are fairly descriptive, the changes are mostly around removing pre-styling on components so that there's more flexibility on the usage end. The big thing is that the `Expander` has been modified so that the slide navigation is continuous in either direction, instead of "rewinding" back to the first one (as Design put it). Example below.
https://github.com/ably/ably-ui/assets/1105768/ec3d53b7-dce1-4213-adf3-2492cbd95ba3
> [WEB-3571] Compare page iterations

- .storybook/styles.css
- package.json
- src/core/Code/component.js
- src/core/ContactFooter/component.js
The solution for getting Tailwind "layer" directives to work was to remove in-component css imports that also used these directives. I previously got rid of all of the TSX ones, seems the import into `website` exposed some JS ones that were left behind.
This fixes the build issue on `website` when upgrading to `^14.0.0`.
> fix: remove Tailwind-dependent CSS imports from non-TSX components

- package.json
- yarn.lock
We need to update a vulnerable dependency: `addsearch-js-client`
[Dependabot warning](https://github.com/ably/ably-ui/security/dependabot/230)
> [CHORE] bump addsearch-js-client to 0.8.11

- package.json
- src/core/MeganavItemsMobile.tsx
- src/core/Slider.tsx
- src/core/Slider/component.css
- src/core/styles.components.css
N/A
Additions:
- adds `ui-section-spacing` and `ui-divider-spacing`, two utility classes to represent the standard vertical spacing standards in the design system
Fixes:
- makes the "Login"/"Logout" link on the Meganav vertically centered instead of like this
- corrects the horizontal alignment of `Slider` navigation errors
> Add basic spacing utilities and fix meganav/slider alignments

- package.json
- tailwind.config.js
- tailwind.extend.js
`ably-ui` 14.0.6 introduced a problem, in that when `src` was omitted from the bundle - the host Tailwind setup in a given app wouldn't have visibility over `ably-ui` assets, due to the package Tailwind config referencing an `src` directory that was no longer there.
This PR extends the list of sources for Tailwind to take into account, and also revises the file types included (the Tailwind docs recommend that `.css` shouldn't be one of them, for instance).
Hard to test. I tested this by pulling version [14.1.1-dev.bdcfda0](https://www.npmjs.com/package/@ably/ui/v/14.1.1-dev.bdcfda0) into `voltaire` and ensuring that the compare pages weren't visually borked.
> [WEB-3840] Fix Tailwind `src` paths

- .gitignore
- package.json
- src/core/MeganavContentUseCases.tsx
- tsconfig.json
WEB-3842
- Updated the menu title
- added some webstorm configs
- In the Storybook page, go to Meganav - Default
-  Click Solutions
- and Dropdown menu appear, the menu on the right should be updated
Updated to this:
> [WEB-3842] - Change Meganav menu name

- package.json
- src/core/styles/Button.stories.tsx
- src/core/styles/buttons.css
- tailwind.config.js
Currently, `ui-btn` styles can be applied to anything, but we only get `disabled` functionality through the native capabilities of `button` elements. When making a link appear and act like a button, we want to be able to provide disabled functionality.
This PR adds an additional class `.ui-btn-disabled`, that when applied to a link element (along with `.ui-btn` or one of the other variants), makes the styled link appear and act like a disabled element.
The main thing here is the extra CSS classes. Everything else in this PR is around presenting these changes in Storybook, mainly porting the MDX page inherited from the previous ably-ui docs over to the preferred Story format.
Pull local, `yarn storybook`, go to the Buttons page under the "CSS" heading, look for the bit on styled links.
> [WEB-3870] chore: add means to style links as buttons with disabled state, port button docs to story

- .storybook/preview.tsx
- package.json
The stories on the [deployed Storybook](https://ably.github.io/ably-ui/?path=/docs/js-components-featured-link--docs) are broken, because of an MSW service worker asset that gets lost because the URL structure changes.
Conditionally changes the URL for the service worker depending on the host. When deployed, we also need to take into account `/ably-ui` in the path (as the URL is `ably.github.ui/ably-ui`)
Hard to test, only comes into action when released.
> [WEB-3870] Fix MSW service worker lookup when deployed

- package.json
- src/core/Footer.tsx
- src/core/Footer/Footer.stories.tsx
- src/core/Meganav.tsx
- src/core/Meganav/Meganav.stories.tsx
- src/core/MeganavContentDevelopers.tsx
- src/core/MeganavItemsDesktop.tsx
- src/core/MeganavItemsMobile.tsx
- src/core/Status.tsx
- src/core/Status/Status.stories.tsx
Supersedes #421 by replacing the embedded status icon from `ably.com/status/embed/icon` with a React component that fetches the status from the statuspage.io API for us
* New `Status` component, requires the `statusUrl` to be set to work reliably
* Added stories for the `Status` component so we view the different states
* Replaced the `iframe` in the `Footer` and `Meganav` components with the `Status`
See commits for details
Pull, run storybook, and view the `Status` components
> [INF-4803] StatusPage component

- package.json
- src/core/Expander.tsx
Fixes some responsive behaviour with the `Expander` component, allowing the height calculations to run again when the window is resized (we would get some undesirable effects before this where the expander would expand too far, or not enough, because the content has changed height as a result of a resize).
Pull down, open up in Storybook, select the "Long Content" story under "Expander", make sure that the expander controls react as you would expect when you resize the window in and out (it should always sit at the full height of the content when expanded, no gaps).
> [WEB-3878] Handle window resizing in Expander

- package.json
- yarn.lock
For some reason, I can't run the rest successfully due to the storybook preview requiring me to install this `http-server` package. After adding this package, the test suite preview building was successful.
> Add http-server package for storybook testing

- package.json
- scripts/compute-colors.ts
- src/core/Pricing/PricingCards.tsx
There are some regressions as a result of https://github.com/ably/ably-ui/pull/510, as the regex for detecting `themeColor` obviously can't detect cases where the argument to `themeColor` is not the class that needs to be processed for theming. We need to figure this out later but be unblocked for now, so some hard-coded references have been added.
Also the regex didn't group properly and omitted `text` from Tailwind class detection, which didn't help.
> fix: structure themeColor detection regex correctly, temporarily hardcode non-literal theming arguments

- src/core/Status.tsx
- src/core/Status/Status.stories.tsx
This PR makes the following alterations which are useful for `WEB-4082`:
- makes the status indicator light smaller as per design request (8x8 instead of 16x16)
- stylises the status description so that capitalised words after the first word are downcased (i.e. My Big Status becomes My big status)
- adjusts the colours of the indicator to better match the colours we have
- ties up the acceptable status types into a type
Additionally, it consolidates the `Status` stories into two so that we can see all the indicators at once in two stories, one with and one without the description label.
> [WEB-4185] update Status appearance, consolidate stories

- package.json
- src/core/Header.tsx
- src/core/Header/Header.stories.tsx
- src/core/Header/HeaderLinks.tsx
The `Header` component, which drives the docs top nav and the upcoming Meganav work, has three sections:
- on the left: the navigable page elements
- in the middle: an optional search bar
- on the right: external links and login buttons
Currently, these sections can be uneven in proportion (as is the case with the docs currently with the left nav hidden until the release of Examples), and since the central search bar partition flexibly fills the available space and centres, this can mean that the search bar is off-centre relative to the page.
This PR divides the header up into three equal sections (when possible), so that the search bar can be centred without being impacted by the unpredictably sized content either side of it. I came to this after concluding that adding a temporary wedge …
> [WEB-4082] Divide header into three equal parts

- package.json
- vite.config.ts
- yarn.lock
I saw [a babel bump PR](https://github.com/ably/ably-ui/pull/686) and wondered how we could reduce babel since we already utilise SWC for package transpilation - tried the SWC react plugin before but it conflicted with Storybook, now it appears to work fine.
It's still used by jest/playwright under the hood, so can't kill it completely, but it's a start towards better performance here.
> chore: switch vite react plugin to use existing swc stuff
